networks:
  proxy-net:
    name: reverse-proxy

volumes:
  conf:    {}
  html:    {}
  vhost:   {}
  certs:   {}
  dhparam: {}
  acme:    {}

services:

  nginx-proxy:
    image: ghcr.io/nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    networks:
      - proxy-net
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - conf:/etc/nginx/conf.d
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro

  acme-companion:
    image: ghcr.io/nginxproxy/acme-companion:2.2
    container_name: nginx-proxy-acme
    restart: unless-stopped
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
