version: "3.5"

networks:
  app-net: {}
  proxy-net:
    external: true
    name: reverse-proxy

services:

  webapp:
    image: nginx:alpine
    depends_on:
      - phpapp
    environment:
      VIRTUAL_HOST:      example.com
      LETSENCRYPT_HOST:  example.com
      LETSENCRYPT_EMAIL: service@example.com
    networks:
      - app-net
      - proxy-net
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./vhost.conf:/etc/nginx/conf.d/default.conf

  ### App service ###
  phpapp:
    image: php:8.1-fpm-alpine
    networks:
      - app-net
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
