version: "3.5"

### Networks ###
networks:
  app-network: {}
  pri-network:
    external: true
    name: reverse-proxy

### Services ###
services:

  ### Web service ###
  webapp:
    image: nginx:alpine
    depends_on:
      - phpapp
    environment:
      VIRTUAL_HOST:      example.com
      LETSENCRYPT_HOST:  example.com
      LETSENCRYPT_EMAIL: service@example.com
    networks:
      - app-network
      - pri-network
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./vhost.conf:/etc/nginx/conf.d/default.conf

  ### App service ###
  phpapp:
    image: php:7.3-fpm-alpine
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
